[package]
name = "graphite-desktop-platform-win"
version = "0.0.0"
description = "Graphite Desktop Platform Windows"
authors = ["Graphite Authors <contact@graphite.art>"]
license = "Apache-2.0"
repository = ""
edition = "2024"
rust-version = "1.87"

[[bin]]
name = "graphite"
path = "src/main.rs"

[dependencies]
graphite-desktop = { path = "../.." }

[target.'cfg(target_os = "windows")'.build-dependencies]
winres = "0.1"
