[package]
name = "graphene-application-io"
version = "0.1.0"
edition = "2024"
description = "graphene application io interface"
authors = ["Graphite Authors <contact@graphite.art>"]
license = "MIT OR Apache-2.0"

[features]
wasm = ["dep:web-sys"]
wgpu = ["dep:wgpu"]

[dependencies]
# Local dependencies
dyn-any = { workspace = true }
core-types = { workspace = true }
vector-types = { workspace = true }
text-nodes = { workspace = true }

# Workspace dependencies
glam = { workspace = true }
serde = { workspace = true }
log = { workspace = true }

# Optional workspace dependencies
web-sys = { workspace = true, optional = true }
wgpu = { workspace = true, optional = true }
