accepted = [
	"Apache-2.0 WITH LLVM-exception", # Keep this list in sync with those in `/deny.toml`
	"Apache-2.0", # Keep this list in sync with those in `/deny.toml`
	"BSD-2-Clause", # Keep this list in sync with those in `/deny.toml`
	"BSD-3-Clause", # Keep this list in sync with those in `/deny.toml`
	"BSL-1.0", # Keep this list in sync with those in `/deny.toml`
	"CC0-1.0", # Keep this list in sync with those in `/deny.toml`
	"CDLA-Permissive-2.0", # Keep this list in sync with those in `/deny.toml`
	"ISC", # Keep this list in sync with those in `/deny.toml`
	"MIT-0", # Keep this list in sync with those in `/deny.toml`
	"MIT", # Keep this list in sync with those in `/deny.toml`
	"MPL-2.0", # Keep this list in sync with those in `/deny.toml`
	"OpenSSL", # Keep this list in sync with those in `/deny.toml`
	"Unicode-3.0", # Keep this list in sync with those in `/deny.toml`
	"Unicode-DFS-2016", # Keep this list in sync with those in `/deny.toml`
	"Zlib", # Keep this list in sync with those in `/deny.toml`
	"NCSA", # Keep this list in sync with those in `/deny.toml`
	"bzip2-1.0.6", # Keep this list in sync with those in `/deny.toml`
	"OFL-1.1", # Keep this list in sync with those in `/deny.toml`
]
workarounds = ["ring"]
ignore-build-dependencies = true
ignore-dev-dependencies = true
# Clearly Defined's API would occasionally (every few months) return errors for at least a full day (maybe some weird rate limiting?), but we can just disable to perform local checking (see #1653)
no-clearly-defined = true

# https://raw.githubusercontent.com/briansmith/webpki/main/LICENSE
# is the ISC license but test code within the repo is BSD-3-Clause, but is not compiled into the crate when we use it
[webpki.clarify]
license = "ISC"
[[webpki.clarify.files]]
path = "LICENSE"
checksum = "5b698ca13897be3afdb7174256fa1574f8c6892b8bea1a66dd6469d3fe27885a"

[rustls-webpki.clarify]
license = "ISC"
[[rustls-webpki.clarify.files]]
path = "LICENSE"
checksum = "5b698ca13897be3afdb7174256fa1574f8c6892b8bea1a66dd6469d3fe27885a"
