edition = "2021"
hard_tabs = true
max_width = 200
newline_style = "Unix"
use_try_shorthand = true

# Maybe enable these in the future when they're stabilized
# normalize_comments = true
# normalize_doc_attributes = true
# struct_lit_width = 35
# where_single_line = true
# match_block_trailing_comma = true # https://github.com/rust-lang/rustfmt/issues/3380
# control_brace_style = "ClosingNextLine" # https://github.com/rust-lang/rustfmt/issues/3377
# blank_lines_lower_bound = 1 # https://github.com/rust-lang/rustfmt/issues/3382
