[workspace]
members = ["rawkit-proc-macros"]
resolver = "2"

[workspace.dependencies]
quote = "1.0"
syn = "2.0"

[package]
name = "rawkit"
version = "0.1.0"
edition = "2024"
authors = ["Graphite Authors <contact@graphite.art>"]
description = "A library to extract images from camera raw files"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["raw", "tiff", "camera", "image"]
categories = ["multimedia::images", "multimedia::encoding"]
homepage = "https://github.com/GraphiteEditor/Graphite/tree/master/libraries/rawkit"
repository = "https://github.com/GraphiteEditor/Graphite/tree/master/libraries/rawkit"
documentation = "https://docs.rs/rawkit"

[features]
rawkit-tests = ["dep:image", "dep:libraw-rs", "dep:reqwest", "dep:rayon"]

[dependencies]
# Local dependencies
rawkit-proc-macros = { version = "0.1.0", path = "rawkit-proc-macros" }

# Required dependencies
bitstream-io = "4.9.0"
num_enum = "0.7.5"
thiserror = "2.0.17"

# Optional dependencies (should be dev dependencies, but Cargo currently doesn't allow optional dev dependencies)
image = { version = "0.25.9", optional = true }
reqwest = { version = "0.12.26", optional = true, features = ["blocking"] }
libraw-rs = { version = "0.0.4", optional = true }
rayon = { version = "1.11.0", optional = true }
