[package]
name = "path-bool-nodes"
version = "0.1.0"
edition = "2024"
description = "Path boolean operation nodes for Graphene"
authors = ["Graphite Authors <contact@graphite.art>"]
license = "MIT OR Apache-2.0"

[dependencies]
# Local dependencies
dyn-any = { workspace = true }
core-types = { workspace = true }
graphic-types = { workspace = true }
node-macro = { workspace = true }
glam = { workspace = true }
specta = { workspace = true }
log = { workspace = true }
path-bool = { workspace = true }
serde = { workspace = true }
vector-types = { workspace = true }
