[package]
name = "rawkit-proc-macros"
version = "0.1.0"
edition = "2024"
authors = ["Graphite Authors <contact@graphite.art>"]
description = "Procedural macros for Rawkit"
license = "MIT OR Apache-2.0"
readme = "README.md"
homepage = "https://github.com/GraphiteEditor/Graphite/tree/master/libraries/rawkit/rawkit-proc-macros"
repository = "https://github.com/GraphiteEditor/Graphite/tree/master/libraries/rawkit/rawkit-proc-macros"
documentation = "https://docs.rs/rawkit-proc-macros"

[lib]
proc-macro = true

[dependencies]
# Workspace dependencies
quote = { workspace = true }
syn = { workspace = true }

# Required dependencies
toml = "0.9.10+spec-1.1.0"
proc-macro2 = "1.0.103"
