[package]
name = "tag-derive"
version = "0.0.1"
publish = false
edition = "2021"
authors = ["Graphite Authors <contact@graphite.rs>"]
description = "Derive macro for the Tag trait in Rawkit"
license = "MIT OR Apache-2.0"
repository = "https://github.com/GraphiteEditor/Graphite/tree/master/libraries/rawkit/tag-derive"

[lib]
proc-macro = true

[dependencies]
# Workspace dependencies
quote = { workspace = true }
syn = { workspace = true }
