[package]
name = "third-party-licenses"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
scraper = "0.22"
serde = { workspace = true }
serde_json = { workspace = true }
