[package]
name = "rendering"
version = "0.1.0"
edition = "2024"
description = "SVG rendering for Graphene"
authors = ["Graphite Authors <contact@graphite.art>"]
license = "MIT OR Apache-2.0"

[dependencies]
# Local dependencies
dyn-any = { workspace = true }
core-types = { workspace = true }

# Workspace dependencies
glam = { workspace = true }
serde = { workspace = true }
base64 = { workspace = true }
log = { workspace = true }
num-traits = { workspace = true }
usvg = { workspace = true }
kurbo = { workspace = true }
vector-types = { workspace = true }
graphic-types = { workspace = true }


# Workspace dependencies
vello = { workspace = true }
