[package]
name = "build-camera-data"
version = "0.0.1"
publish = false
edition = "2021"
authors = ["Graphite Authors <contact@graphite.rs>"]
description = "Procedural macro to build the camera data into rust code"
license = "MIT OR Apache-2.0"
repository = "https://github.com/GraphiteEditor/Graphite/tree/master/libraries/raw-rs/build-camera-data"

[lib]
proc-macro = true

[dependencies]
# Workspace dependencies
quote = { workspace = true }
syn = { workspace = true }
proc-macro2 = { workspace = true }
toml = "0.8.15"
