[package]
name = "graphene-core"
version = "0.1.0"
edition = "2024"
description = "Core utility nodes for Graphene"
authors = ["Graphite Authors <contact@graphite.art>"]
license = "MIT OR Apache-2.0"

[features]
default = ["serde"]

[dependencies]
# Local dependencies
core-types = { workspace = true }
raster-types = { workspace = true }
graphic-types = { workspace = true }
node-macro = { workspace = true }

# Workspace dependencies
dyn-any = { workspace = true }
glam = { workspace = true }
log = { workspace = true }
serde_json = { workspace = true }
specta = { workspace = true }

# Optional workspace dependencies
serde = { workspace = true, optional = true }
