[package]
name = "graphene-cli"
version = "0.1.0"
edition = "2021"
description = "CLI interface for the graphene language"
authors = ["Graphite Authors <contact@graphite.rs>"]
license = "MIT OR Apache-2.0"

[features]
default = ["wgpu"]
wgpu = ["wgpu-executor", "gpu", "graphene-std/wgpu"]
wayland = ["graphene-std/wayland"]
profiling = ["wgpu-executor/profiling"]
passthrough = ["wgpu-executor/passthrough"]
gpu = [
	"interpreted-executor/gpu",
	"graphene-std/gpu",
	"graphene-core/gpu",
	"wgpu-executor",
	"gpu-executor",
]

[dependencies]
# Local dependencies
graphene-std = { path = "../gstd", features = ["serde"] }
interpreted-executor = { path = "../interpreted-executor" }

# Workspace dependencies
log = { workspace = true }
bitflags = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
bezier-rs = { workspace = true }
glam = { workspace = true }
graph-craft = { workspace = true }
dyn-any = { workspace = true }
graphene-core = { workspace = true }
futures = { workspace = true }
fern = { workspace = true }
chrono = { workspace = true }
wgpu = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
image = { workspace = true, default-features = false, features = [
	"bmp",
	"png",
] }

# Optional local dependencies
wgpu-executor = { path = "../wgpu-executor", optional = true }
gpu-executor = { path = "../gpu-executor", optional = true }

# Optional workspace dependencies
wasm-bindgen = { workspace = true, optional = true }
