[package]
name = "brush-nodes"
version = "0.1.0"
edition = "2024"
description = "Brush rendering nodes for Graphene"
authors = ["Graphite Authors <contact@graphite.art>"]
license = "MIT OR Apache-2.0"

[features]
default = ["serde"]
serde = ["dep:serde"]

[dependencies]
# Local dependencies
dyn-any = { workspace = true }
core-types = { workspace = true }
raster-types = { workspace = true }
raster-nodes = { workspace = true }
node-macro = { workspace = true }

# Workspace dependencies
glam = { workspace = true }

# Optional workspace dependencies
serde = { workspace = true, optional = true, features = ["derive"] }

[dev-dependencies]
# Workspace dependencies
tokio = { workspace = true }
