[package]
name = "path-bool"
version = "0.1.0"
rust-version = "1.85"
authors = ["Graphite Authors <contact@graphite.rs>", "Adam Platkeviƒç"]
edition = "2024"
keywords = [
	"bezier",
	"curve",
	"boolean",
	"path",
	"geometry",
	"computational geometry",
	"vector graphics",
	"2d",
	"graphics",
]
categories = ["graphics", "mathematics"]
license = "MIT OR Apache-2.0"

[features]
logging = ["parsing"]
parsing = []
default = ["parsing"]

[dependencies]
glam = "0.29.0"
regex = "1.10.6"
slotmap = "1.0.7"
lyon_geom = "1.0"
roots = "0.0.8"
rustc-hash = "2.0.0"
smallvec = "1.13.2"

[dev-dependencies]
glob = "0.3"
svg = "0.18"
resvg = "0.44"
image = "0.25"

# Required dependencies
criterion = { workspace = true }

# Benchmarks
[[bench]]
name = "painted_dreams"
harness = false
[[bench]]
name = "path_segment_intersection"
harness = false
