[package]
name = "path-bool"
version = "0.1.0"
rust-version = "1.79"
authors = ["Graphite Authors <contact@graphite.rs>"]
edition = "2021"
keywords = ["bezier", "boolean", "path", "ops", "operations", "2d"]
categories = ["graphics", "mathematics"]
license = "MIT OR Apache-2.0"


[features]
logging = ["parsing"]
parsing = []
default = ["parsing"]

[dependencies]
glam = "0.28.0"
regex = "1.10.6"
slotmap = "1.0.7"

[dev-dependencies]
glob = "0.3"
svg = "0.13"
resvg = "0.42"
image = "0.24"

# Required dependencies
criterion = { version = "0.5", features = ["html_reports"]}

# Benchmarks
[[bench]]
name = "painted_dreams"
harness = false

[[bench]]
name = "path_segment_intersection"
harness = false
