title = "Graphite"
description = "2D raster & vector editor that melds traditional layers & tools with a modern node-based procedural workflow."
base_url = "https://graphite.rs"
feed_filenames = ["rss.xml"]

compile_sass = true
minify_html = false

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
	{ theme = "kronuz", filename = "syntax-highlighting.css" },
]

[extra]
# Put all your custom variables here
