title = "Graphite"
description = "2D raster & vector editor that melds traditional layers & tools with a modern node-based procedural workflow."
base_url = "https://graphite.art"
feed_filenames = ["rss.xml"]

compile_sass = true
minify_html = false

[markdown.highlighting]
error_on_missing_language = false
theme = "gruvbox-dark-soft"

[extra]
# Put all your custom variables here
