[package]
name = "math-parser"
version = "0.0.0"
rust-version = "1.85"
edition = "2024"
authors = ["Graphite Authors <contact@graphite.rs>"]
description = "Parser for Graphite style mathematics expressions"
license = "MIT OR Apache-2.0"

[dependencies]
thiserror = "2.0"
lazy_static = "1.5"
num-complex = "0.4"
chumsky = { version = "0.10", default-features = false, features = ["std"] }
codespan-reporting = { git = "https://github.com/urisinger/codespan-style-writer.git"}

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "bench"
harness = false
