name: "Deploy Master"

on:
  workflow_run:
    workflows: ["Provide Shaders"]
    types:
      - completed
    branches:
      - master

env:
  CARGO_TERM_COLOR: always
  INDEX_HTML_HEAD_REPLACEMENT: <script defer data-domain="dev.graphite.art" data-api="https://graphite.art/visit/event" src="https://graphite.art/visit/script.hash.js"></script>

jobs:
  deploy:
    # Only run if the shader build succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
      actions: write
    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"

    steps:
      - name: ğŸ“¥ Clone and checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: ğŸ¨ Download pre-built shaders
        run: |
          SHADER_URL="https://raw.githubusercontent.com/${{ vars.ARTIFACTS_REPO_OWNER }}/${{ vars.ARTIFACTS_REPO_NAME }}/${{ vars.ARTIFACTS_REPO_BRANCH }}/rev/${{ github.event.workflow_run.head_sha }}/raster_nodes_shaders_entrypoint.wgsl"
          curl -fsSL "$SHADER_URL" -o raster_nodes_shaders_entrypoint.wgsl
          echo "RASTER_NODES_SHADER_PATH=$(pwd)/raster_nodes_shaders_entrypoint.wgsl" >> $GITHUB_ENV

      - name: ğŸŸ¢ Install the latest Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: ğŸ¦€ Install the latest Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: âš¡ Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.9

      - name: ğŸ“¦ Setup cargo-binstall
        uses: cargo-bins/cargo-binstall@main

      - name: ğŸ“¦ Install wasm-pack and cargo-about
        run: cargo binstall --no-confirm --force wasm-pack cargo-about

      - name: ğŸ“¦ Install wasm-opt (binaryen)
        run: sudo apt-get update && sudo apt-get install -y binaryen

      - name: ğŸš§ Install build dependencies
        run: |
          cd frontend
          npm run setup

      - name: âœ‚ Replace template in <head> of index.html
        run: |
          sed -i "s|<!-- INDEX_HTML_HEAD_REPLACEMENT -->|$INDEX_HTML_HEAD_REPLACEMENT|" frontend/index.html

      - name: ğŸŒ Build Graphite web code
        env:
          NODE_ENV: production
        run: |
          cd frontend
          npm run build

      - name: ğŸ“¤ Publish to Cloudflare Pages
        id: cloudflare
        uses: cloudflare/pages-action@1
        continue-on-error: true
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: graphite-dev
          directory: frontend/dist

      - name: ğŸ’¬ Comment build link URL to commit hash page on GitHub
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/commits/$(git rev-parse HEAD)/comments \
            -f body="| ğŸ“¦ **Build Complete for** $(git rev-parse HEAD) |
          |-|
          | ${{ steps.cloudflare.outputs.url }} |"

      - name: ğŸ“ƒ Generate code documentation info for website
        run: |
          cd tools/editor-message-tree
          cargo run
          cd ../..
          mkdir -p artifacts-generated
          mv website/generated/hierarchical_message_system_tree.txt artifacts-generated/hierarchical_message_system_tree.txt

      - name: ğŸ’¿ Obtain cache of auto-generated code docs artifacts, to check if they've changed
        id: cache-website-code-docs
        uses: actions/cache/restore@v3
        with:
          path: artifacts
          key: website-code-docs

      - name: ğŸ” Check if auto-generated code docs artifacts changed
        id: website-code-docs-changed
        run: |
          if ! diff --brief --recursive artifacts-generated artifacts; then
            echo "Auto-generated code docs artifacts have changed."
            rm -rf artifacts
            mv artifacts-generated artifacts
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "Auto-generated code docs artifacts have not changed."
            rm -rf artifacts
            rm -rf artifacts-generated
          fi

      - name: ğŸ’¾ Save cache of auto-generated code docs artifacts
        if: steps.website-code-docs-changed.outputs.changed == 'true'
        uses: actions/cache/save@v3
        with:
          path: artifacts
          key: ${{ steps.cache-website-code-docs.outputs.cache-primary-key }}

      - name: â™»ï¸ Trigger website rebuild if the auto-generated code docs artifacts have changed
        if: steps.website-code-docs-changed.outputs.changed == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          rm -rf artifacts
          gh workflow run website.yml --ref master
