name: "Deploy Master"

on:
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always
  INDEX_HTML_HEAD_REPLACEMENT: <script defer data-domain="dev.graphite.art" data-api="https://graphite.art/visit/event" src="https://graphite.art/visit/script.hash.js"></script>

jobs:
  deploy:
    runs-on: self-hosted
    permissions:
      contents: write
      deployments: write
      actions: write
    env:
      RUSTC_WRAPPER: /usr/bin/sccache
      CARGO_INCREMENTAL: 0
      SCCACHE_DIR: /var/lib/github-actions/.cache

    steps:
      - name: ğŸ“¥ Clone and checkout repository
        uses: actions/checkout@v3

      - name: ğŸ—‘ Clear wasm-bindgen cache
        run: rm -r ~/.cache/.wasm-pack || true

      - name: ğŸŸ¢ Install the latest Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: ğŸš§ Install build dependencies
        run: |
          cd frontend
          npm run setup

      - name: ğŸ¦€ Install the latest Rust
        run: |
          rustup update stable

      - name: âœ‚ Replace template in <head> of index.html
        run: |
          sed -i "s|<!-- INDEX_HTML_HEAD_REPLACEMENT -->|$INDEX_HTML_HEAD_REPLACEMENT|" frontend/index.html

      - name: ğŸŒ Build Graphite web code
        env:
          NODE_ENV: production
        run: |
          cd frontend
          mold -run npm run build

      - name: ğŸ“¤ Publish to Cloudflare Pages
        id: cloudflare
        uses: cloudflare/pages-action@1
        continue-on-error: true
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: graphite-dev
          directory: frontend/dist

      - name: ğŸ’¬ Comment build link URL to commit hash page on GitHub
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/commits/$(git rev-parse HEAD)/comments \
            -f body="| ğŸ“¦ **Build Complete for** $(git rev-parse HEAD) |
          |-|
          | ${{ steps.cloudflare.outputs.url }} |"

      - name: ğŸ“ƒ Generate code documentation info for website
        run: |
          cd tools/editor-message-tree
          cargo run
          cd ../..
          mkdir -p artifacts-generated
          mv website/generated/hierarchical_message_system_tree.txt artifacts-generated/hierarchical_message_system_tree.txt

      - name: ğŸ’¿ Obtain cache of auto-generated code docs artifacts, to check if they've changed
        id: cache-website-code-docs
        uses: actions/cache/restore@v3
        with:
          path: artifacts
          key: website-code-docs

      - name: ğŸ” Check if auto-generated code docs artifacts changed
        id: website-code-docs-changed
        run: |
          if ! diff --brief --recursive artifacts-generated artifacts; then
            echo "Auto-generated code docs artifacts have changed."
            rm -rf artifacts
            mv artifacts-generated artifacts
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "Auto-generated code docs artifacts have not changed."
            rm -rf artifacts
            rm -rf artifacts-generated
          fi

      - name: ğŸ’¾ Save cache of auto-generated code docs artifacts
        if: steps.website-code-docs-changed.outputs.changed == 'true'
        uses: actions/cache/save@v3
        with:
          path: artifacts
          key: ${{ steps.cache-website-code-docs.outputs.cache-primary-key }}

      - name: â™»ï¸ Trigger website rebuild if the auto-generated code docs artifacts have changed
        if: steps.website-code-docs-changed.outputs.changed == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          rm -rf artifacts
          gh workflow run website.yml --ref master
