[package]
name = "graphene-std"
version = "0.1.0"
edition = "2024"
description = "Graphene standard library"
authors = ["Graphite Authors <contact@graphite.art>"]
license = "MIT OR Apache-2.0"

[features]
default = ["wasm", "wgpu"]
gpu = []
wgpu = ["gpu", "graph-craft/wgpu", "graphene-application-io/wgpu"]
wasm = [
	"wasm-bindgen",
	"wasm-bindgen-futures",
	"web-sys",
	"graphene-application-io/wasm",
	"image/png",
]
image-compare = []
vello = ["gpu"]
resvg = []
shader-nodes = ["raster-nodes/shader-nodes"]

[dependencies]
# Local dependencies
dyn-any = { workspace = true }
graph-craft = { workspace = true }
wgpu-executor = { workspace = true }
core-types = { workspace = true }
vector-types = { workspace = true }
graphic-types = { workspace = true }
blending-nodes = { workspace = true }
text-nodes = { workspace = true }
transform-nodes = { workspace = true }
vector-nodes = { workspace = true }
path-bool-nodes = { workspace = true }
math-nodes = { workspace = true }
rendering = { workspace = true }
graphene-application-io = { workspace = true }
raster-nodes = { workspace = true }
brush-nodes = { workspace = true }
graphene-core = { workspace = true }
graphic-nodes = { workspace = true }

# Workspace dependencies
log = { workspace = true }
glam = { workspace = true }
node-macro = { workspace = true }
reqwest = { workspace = true }
image = { workspace = true }
base64 = { workspace = true }

# Optional workspace dependencies
wasm-bindgen = { workspace = true, optional = true }
wasm-bindgen-futures = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }
vello = { workspace = true }
vello_encoding = { workspace = true }
web-sys = { workspace = true, optional = true, features = [
	"Window",
	"CanvasRenderingContext2d",
	"ImageData",
	"Document",
	"Navigator",
	"Gpu",
	"HtmlCanvasElement",
	"HtmlImageElement",
	"ImageBitmapRenderingContext",
] }

[dev-dependencies]
tokio = { workspace = true }
